apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rstudio
spec:
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio-server
        image: rocker/rstudio
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3838
          name: rstudio-port
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  type: NodePort
  ports:
  - port: 3838
    targetPort: rstudio-port
    nodePort: 8787
    protocol: TCP
  selector:
    app: rstudio
